/**
 * 
 */
package exceptionHandling;

/**
 * @author hp
 *
 */
public class ExceptionCodeValue {
	
		public int arithmeticExceptionCode = 123;
		public String arithmeticExceptionMessage = "we have exception in Calucation time";

		public int nullPointerExceptionCode = 011;
		public String nullPointerExceptionMessage = "we have exception in Object retrival time";

		public int numberFormatExceptionCode = 65;
		public String numberFormatExceptionMessage = "we have exception in convert to Number time";

		public int arrayIndexOutOfBoundsExceptionCode = 24;
		public String arrayIndexOutOfBoundsExceptionMessage = "we have exception in Calucation time";

		public int exceptionCode = 100;
		public String exceptionMessage = "we have exception";


		}
